# Generated by Django 6.0.2 on 2026-03-11 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectid', models.CharField(max_length=50, unique=True)),
                ('project_name', models.CharField(max_length=200)),
                ('required_workforce', models.IntegerField(default=0)),
                ('risk_threshold_percent', models.IntegerField(default=50)),
                ('warning_threshold_percent', models.IntegerField(default=75)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'projects',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PublicHolidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_name', models.CharField(max_length=255)),
                ('holiday_date', models.DateField()),
                ('day', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'public_holidays',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.user')),
            ],
            options={
                'db_table': 'sessions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_from', models.DateField(blank=True, null=True)),
                ('assigned_till', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.project')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.user')),
            ],
            options={
                'db_table': 'project_assignments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Paid', 'Paid'), ('Sick', 'Sick'), ('WFH', 'WFH'), ('Half Day', 'Half Day'), ('Conference', 'Conference')], max_length=20)),
                ('leave_status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_half_day', models.BooleanField(default=False)),
                ('half_day_session', models.CharField(blank=True, choices=[('First Half', 'First Half'), ('Second Half', 'Second Half')], max_length=20, null=True)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.project')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.user')),
            ],
            options={
                'db_table': 'leave_applications',
                'managed': True,
            },
        ),
    ]
