# Generated by Django 6.0.2 on 2026-03-31 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allocated_leaves',
            field=models.IntegerField(default=0),
        ),
    ]
